from typing import List, Optional
from pydantic import BaseModel


class Data(BaseModel):
    DocumentWeight: float
    ServiceType: str
    UndeliveryReasons: Optional[str]
    LoyaltyCardSender: str
    RecipientFullName: Optional[str]
    FactualWeight: str
    MarketplacePartnerToken: Optional[str]
    CounterpartySenderDescription: str
    InternationalDeliveryType: Optional[str]
    CargoType: str
    PayerType: str
    SeatsAmount: str
    ScheduledDeliveryDate: str
    DocumentCost: str
    CardMaskedNumber: Optional[str]
    OwnerDocumentType: Optional[str]
    ExpressWaybillPaymentStatus: str
    ExpressWaybillAmountToPay: float
    AfterpaymentOnGoodsCost: int
    SumBeforeCheckWeight: int
    CheckWeight: int
    PaymentMethod: str
    AdjustedDate: Optional[str]
    Number: str
    PhoneSender: str
    TrackingUpdateDate: str
    CalculatedWeight: Optional[str]
    WarehouseRecipient: str
    WarehouseSender: str
    DateCreated: str
    DateScan: str
    DateReturnCargo: Optional[str]
    DateMoving: Optional[str]
    DateFirstDayStorage: Optional[str]
    DatePayedKeeping: Optional[str]
    RecipientAddress: str
    RecipientDateTime: Optional[str]
    RefCityRecipient: str
    RefCitySender: str
    RefSettlementRecipient: str
    RefSettlementSender: str
    SenderAddress: str
    SenderFullNameEW: str
    ClientBarcode: str
    CitySender: str
    CityRecipient: str
    CargoDescriptionString: str
    AnnouncedPrice: int
    AdditionalInformationEW: str
    ActualDeliveryDate: Optional[str]
    StatusCode: str
    PostomatV3CellReservationNumber: bool
    AmountToPay: Optional[str]
    AmountPaid: Optional[str]
    RefEW: str
    VolumeWeight: str
    CheckWeightMethod: Optional[str]
    OwnerDocumentNumber: Optional[str]
    LastCreatedOnTheBasisNumber: Optional[str]
    LastCreatedOnTheBasisDateTime: Optional[str]
    LastTransactionDateTimeGM: Optional[str]
    PaymentStatus: Optional[str]
    PaymentStatusDate: Optional[str]
    LastAmountTransferGM: Optional[str]
    LastAmountReceivedCommissionGM: int
    LastCreatedOnTheBasisPayerType: Optional[str]
    DeliveryTimeframe: Optional[str]
    LastTransactionStatusGM: Optional[str]
    Status: str
    Redelivery: int
    RedeliveryNum: Optional[str]
    RedeliverySum: int
    RedeliveryPayer: Optional[str]
    UndeliveryReasonsDate: Optional[str]
    UndeliveryReasonsSubtypeDescription: Optional[str]
    RecipientWarehouseTypeRef: str
    WarehouseRecipientInternetAddressRef: str
    WarehouseRecipientNumber: int
    WarehouseRecipientRef: str
    CategoryOfWarehouse: str
    WarehouseRecipientAddress: str
    WarehouseSenderInternetAddressRef: str
    WarehouseSenderAddress: str
    CounterpartyType: str
    CounterpartySenderType: str
    AviaDelivery: int
    BarcodeRedBox: Optional[str]
    CargoReturnRefusal: bool
    DaysStorageCargo: str
    Packaging: List
    PartialReturnGoods: List
    SecurePayment: bool
    StorageAmount: Optional[str]
    StoragePrice: Optional[str]
    PossibilityCreateRedirecting: bool
    PossibilityCreateReturn: bool
    PossibilityCreateRefusal: bool
    PossibilityChangeEW: bool
    PossibilityChangeCash2Card: bool
    PossibilityChangeDeliveryIntervals: bool
    CounterpartyRecipientDescription: Optional[str]
    CreatedOnTheBasis: Optional[str]
    FreeShipping: Optional[str]
    InternetDocumentDescription: Optional[str]
    LastCreatedOnTheBasisDocumentType: Optional[str]
    LoyaltyCardRecipient: Optional[str]
    PhoneRecipient: Optional[str]
    RecipientFullNameEW: Optional[str]
    RedeliveryPaymentCardDescription: Optional[str]
    RedeliveryServiceCost: Optional[str]
    RedeliveryPaymentCardRef: Optional[str]


class TrackingResponse(BaseModel):
    success: bool
    data: List[Data]
    errors: List
    warnings: List
    info: List
    messageCodes: List
    errorCodes: List
    warningCodes: List
    infoCodes: List
